No need to wait after Wire.requestFrom()
Sensirion/arduino-sht pull request #1
Opened 2017-08-12 07:44 UTC by Koepel

2017-08-12 16:36 UTC, winkj requested changes

2017-08-12 16:36 UTC, winkj commented on SHTSensor.cpp
> -    if (tries++ >= MAX_I2C_READ_TRIES) {
Looks good overall, but MAX_I2C_READ_TRIES should be removed, too, since it's not needed anymore

2017-08-12 19:11 UTC, Koepel commented on SHTSensor.cpp
> -    if (tries++ >= MAX_I2C_READ_TRIES) {
Yes, the MAX_I2C_READ_TRIES can be removed as well.

2017-08-12 20:55 UTC, winkj commented
Please also remove MAX_I2C_READ_TRIES in SHTSensor.h, and combine the three commits into one since they are one logical change

2017-08-12 22:30 UTC, Koepel commented
I'm sorry, but I can't find a Merge button for an existing Pull Request. When I make a new Pull Request I'm redirected to this existing Pull Request.

2017-08-14 23:34 UTC, winkj commented
Your master repository still has three commits that should be squashed into one; you can either do that with "git rebase", or with a temporary branch. Let me know if you need any help with that!

2017-08-14 23:37 UTC, winkj commented
@Koepel actually, I can squash them during the merge process; I'd still recommend to bundle these changes in the future, but for this request, we can do that.

@abrauchli comments?

2017-08-15 05:49 UTC, abrauchli commented
@Koepel lgtm, thanks, will squash-merge.

2017-08-15 09:01 UTC, abrauchli commented
Merged as d999cbce3d604e6118d84e119f6cc3a94c5db488

2017-08-15 09:01 UTC, closed without merging